### ISSUE TITLE
Handling Register Failed and Login Failed

### ISSUE THREAD

**Issue by ArjunSaili1** [CSC207-2022F-UofT/course-project-got-it#28]
Currently register failed and login failed are fully implemented.

There should be a back button on each so the user can try again.

To do this, we should implement some type of back function on the presenter that controllers for login and register call respectively call. 

We maybe should consider creating a backable interface that is implemented by controllers where the user may go back. 

This interface could require a back function, that is implemented in the presenter. 

Implementing the actually going back process shouldn't be difficult, presenter keeps track of all screens that were shown in a hashmap.

Note: the register functionality is completed but not currently merged with main. Please use PR #27 to work on this.

**Comment by pranavag10** [comment]
Done with #37
