### ISSUE TITLE
[Feature 6] Users can change the order's status [Delivered, Cancelled, Picked up]

### ISSUE THREAD

**Issue by pranavag10** [CSC207-2022F-UofT/course-project-got-it#7]
Users can update the status of their delivery request during the delivery process.

**Comment by haileyngg** [comment]
This feature will not be implemented. In addition to scoping issues, we decided not to implement this feature as updates will be handled by the application itself. There is an estimated time for each request to be completed and once the timer is completed the request would be indicated as completed.
